<?php

return [
    'admin_username' => getenv('KIMTHAM_ADMIN_USERNAME') ?: 'admin',
    // Set this on hosting with a value generated by password_hash().
    // The admin login is intentionally disabled when the hash is missing.
    'admin_password_hash' => getenv('KIMTHAM_ADMIN_PASSWORD_HASH') ?: '',
    'notification_email' => getenv('KIMTHAM_NOTIFICATION_EMAIL') ?: 'hello@kimtham.id.vn',
];
